export default {
  REPORT_GET_ALL_CUSTOMER_ATTEMPT: 'REPORT_GET_ALL_CUSTOMER_ATTEMPT',
  REPORT_GET_ALL_CUSTOMER_SUCCESS: 'REPORT_GET_ALL_CUSTOMER_SUCCESS',
  REPORT_GET_ALL_CUSTOMER_FAILURE: 'REPORT_GET_ALL_CUSTOMER_FAILURE',

  REPORT_GET_CUSTOMER_INFO_ATTEMPT: 'REPORT_GET_CUSTOMER_INFO_ATTEMPT',
  REPORT_GET_CUSTOMER_INFO_SUCCESS: 'REPORT_GET_CUSTOMER_INFO_SUCCESS',
  REPORT_GET_CUSTOMER_INFO_FAILURE: 'REPORT_GET_CUSTOMER_INFO_FAILURE',

  REPORT_GET_ALL_VENDOR_ATTEMPT: 'REPORT_GET_ALL_VENDOR_ATTEMPT',
  REPORT_GET_ALL_VENDOR_SUCCESS: 'REPORT_GET_ALL_VENDOR_SUCCESS',
  REPORT_GET_ALL_VENDOR_FAILURE: 'REPORT_GET_ALL_VENDOR_FAILURE',

  REPORT_GET_VENDOR_INFO_ATTEMPT: 'REPORT_GET_VENDOR_INFO_ATTEMPT',
  REPORT_GET_VENDOR_INFO_SUCCESS: 'REPORT_GET_VENDOR_INFO_SUCCESS',
  REPORT_GET_VENDOR_INFO_FAILURE: 'REPORT_GET_VENDOR_INFO_FAILURE',

  REPORT_GET_ALL_TRANSACTION_ATTEMPT: 'REPORT_GET_ALL_TRANSACTION_ATTEMPT',
  REPORT_GET_ALL_TRANSACTION_SUCCESS: 'REPORT_GET_ALL_TRANSACTION_SUCCESS',
  REPORT_GET_ALL_TRANSACTION_FAILURE: 'REPORT_GET_ALL_TRANSACTION_FAILURE',

};
