export default {
  REPORT_GET_CUSTOMER_INFO_ATTEMPT: 'REPORT_GET_CUSTOMER_INFO_ATTEMPT',
  REPORT_GET_CUSTOMER_INFO_SUCCESS: 'REPORT_GET_CUSTOMER_INFO_SUCCESS',
  REPORT_GET_CUSTOMER_INFO_FAILURE: 'REPORT_GET_CUSTOMER_INFO_FAILURE',

  REPORT_GET_ALL_TRANSACTION_ATTEMPT: 'REPORT_GET_ALL_TRANSACTION_ATTEMPT',
  REPORT_GET_ALL_TRANSACTION_SUCCESS: 'REPORT_GET_ALL_TRANSACTION_SUCCESS',
  REPORT_GET_ALL_TRANSACTION_FAILURE: 'REPORT_GET_ALL_TRANSACTION_FAILURE',

};
