export default {
  REPORT_GET_CUSTOMER_INFO_ATTEMPT: 'REPORT_GET_CUSTOMER_INFO_ATTEMPT',
  REPORT_GET_CUSTOMER_INFO_SUCCESS: 'REPORT_GET_CUSTOMER_INFO_SUCCESS',
  REPORT_GET_CUSTOMER_INFO_FAILURE: 'REPORT_GET_CUSTOMER_INFO_FAILURE'

};
